name = "microbit_bsp"
description = "Board Support Package for the BBC micro:bit v1"
long-description = '''# microbit BSP

Board Support Package for the BBC micro:bit https://microbit.org/

This crate is a snapshot of [Ada Drivers
Library](https://github.com/AdaCore/Ada_Drivers_Library/tree/master/middleware).

Any bug report, issue, contribution must be adressed to the [Ada Drivers
Library](https://github.com/AdaCore/Ada_Drivers_Library/) repo.

'''
version = "0.3.0-dev"
licenses = "BSD-3-Clause"
website = "https://github.com/AdaCore/Ada_Drivers_Library/"
tags = ["embedded", "nostd", "microbit", "bbc", "nrf51", "bsp"]

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <chouteau@adacore.com>", "Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["Fabien-Chouteau", "JeremyGrosser"]

[[depends-on]]
nrf5x_hal = "~0.2.0"
embedded_components = "~0.2.0"

[configuration.values]
nrf5x_hal.Device = "nrf51"

[[pins]]
nrf5x_hal = { url='https://github.com/JeremyGrosser/nrf5x_hal' }
embedded_components = { url='https://github.com/JeremyGrosser/embedded_components' }
